### ISSUE TITLE
aaspe-aascore not understood by a plugin

### ISSUE THREAD

**Issue by martafullen** [eclipse-aaspe/aaspe-common#1]
```
[AasxPluginGenericForms] Error: loading additional options ($D:\idta\eclipse-aaspe\aaspe\src\AasxPluginGenericForms\bin\Debug\net6.0-windows\IDTA 02004-1-2_Template_Handover Documentation.add-options.json): Error resolving type specified in JSON 'AasCore.Aas3_0.ConceptDescription, AasCore.Aas3_0'. Path 'Records[0].ConceptDescriptions[0].$type', line 492, position 70. Error resolving type specified in JSON 'AasCore.Aas3_0.ConceptDescription, AasCore.Aas3_0'. Path 'Records[0].ConceptDescriptions[0].$type', line 492, position 70.
InnerException: Could not load assembly 'AasCore.Aas3_0'. at    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at AasxIntegrationBase.AasxPluginOptionsBase.LoadOptionsFromJson[T](String json, String fnInfo, JsonSerializerSettings settings, LogInstance log, UpgradeMapping[] upgrades) in D:\idta\eclipse-aaspe\aaspe\src\AasxIntegrationBase\AasxPluginOptionsBase.cs:line 121
at AasxIntegrationBase.AasxPluginOptionsBase.TryLoadAdditionalOptionsFromAssemblyDir[T](String pluginName, Assembly assy, JsonSerializerSettings settings, LogInstance log, UpgradeMapping[] upgrades) in D:\idta\eclipse-aaspe\aaspe\src\AasxIntegrationBase\AasxPluginOptionsBase.cs:line 189.Inner message: Could not load assembly 'AasCore.Aas3_0'.
```

**Comment by martafullen** [comment]
AasxPluginGenericForms

**Comment by Freezor** [comment]
@martafullen I had a look here, and I have some questions:

- How do you build the nuget for the aaspe-common? I cannot find any existing build configuration.
- Is the csproj configured correctly? I can see a PackageId but not the assembly name.

So far I think this might be the problem. It looks like your plugin wants to reference AasCore.Aas3_0, but it does not exist and the only naming is `<PackageId>Aaspe.AasCore</PackageId>`. Maybe we should add `<AssemblyName>AasCore.Aas3_0</AssemblyName>` and try again.
